// F1 fattening steers of 石黒牛舎 (52 10.4 ★, 4.3): the frames, drawn from part
// shapes (body, neck, legs, tail) with a hand-drawn head, then checked at 1x on
// the barn's straw and at 8x. Letters: O outline #1B1733, k coat #2B2A30,
// l light #45434C (the top of the back and neck under the tubes, the planes
// behind the shoulder and in front of the thigh, the forehead), s sheen
// #6E6A78 (the withers, the loin, the hook bones, the ear's top), K deepest
// #1B1733 (belly, far legs, the barrel's underside), e eye #0B0B14, n muzzle
// #3A3F48, N its wet shine #9AA0A8, Y ear tag #FFD23F, y tag shade #D9A441,
// h hoof #3A3F48, W white #E8E4D8, w white shade #C8C2B4.
// The side views face left (mirrored at run time for `right`): a long deep
// barrel with a straight back and a square rump, the head held a little under
// the withers with the neck's crest dipping behind the poll, the near ear out
// behind the poll with its tag hanging under the tip, the jaw clear of the
// dewlap, short legs under the deep body, the tail hanging clear of the
// buttock (a pixel's gap) from the tailhead down past the hock to its switch
// (2026-09-27; the swish frames show it swung out, so shorter). The front view
// (north rail) has its feet on row 19: the front legs under the chest, the
// barrel bulging out past them, a short thick neck under the rail's upper pipe,
// the head low with the broad forehead and the ears straight out with their tags
// between the pipes, the muzzle down in the feed below the lower pipe; the back
// going away up the screen to the square rump. The back
// view (south rail) has its feet on the bottom row: the thighs round either
// side of the tail, the hook and pin bones, the back going away, the neck up
// under the rail and the poll with the ears and tags in the trough (drawn
// without the rail as `rear`: up at dawn in a south pen, head up to the
// aisle). `stand` (20×23, feet on the bottom row): up at dawn in a north pen,
// turned to face the aisle, the head low in front of the broad shoulders, the
// ears out, short legs under the chest.

export const COW_FRAMES: Record<string, Record<string, string[]>> = {
  side: {
    base: [
      '................................',
      '................................',
      '................................',
      '...OOOO......OOOOOOOOOOOOOOO....',
      '..OlllsOOO..OsssllllllssssllOOO.',
      '..OlkkOsssO.OlkkkkkkkkkkklsllkOO',
      '.OlkkkkOOYOOlklkkkkkkkkkklkklO.O',
      '.OlekkkkkykOlklkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'ONnkkOOkkkkkklkkkkkkkkkklkkklO.O',
      'OnnkO..OkkkkkkkkkkkkkkkkklkklO.O',
      'OnnnO...OkkkkkKKKKKKKKKKkkkklO.O',
      '.OOO.....OkKKOKKKKKKKKKKOOOOlO.O',
      '.........OOKKOKKKOOOOKKKOKKkkO.O',
      '..........OlkOKKO....OKO.OkkkO.O',
      '..........OlkOKKO....OKO.OkkkO.O',
      '..........OlkOKKO....OKO.OkkO.OO',
      '..........OlkOKKO....OKKOkkO..Ok',
      '..........OkkOKKO....OKKOkkO...O',
      '..........OhhOOhO....OhOOhhO....',
    ],
    chew: [
      '................................',
      '................................',
      '................................',
      '...OOOO......OOOOOOOOOOOOOOO....',
      '..OlllsOOO..OsssllllllssssllOOO.',
      '..OlkkOsssO.OlkkkkkkkkkkklsllkOO',
      '.OlkkkkOOYOOlklkkkkkkkkkklkklO.O',
      '.OlekkkkkykOlklkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'ONnkkOOkkkkkklkkkkkkkkkklkkklO.O',
      'OnnkkkOOkkkkkkkkkkkkkkkkklkklO.O',
      'OnnnkO..OkkkkkKKKKKKKKKKkkkklO.O',
      '.OOOO....OkKKOKKKKKKKKKKOOOOlO.O',
      '.........OOKKOKKKOOOOKKKOKKkkO.O',
      '..........OlkOKKO....OKO.OkkkO.O',
      '..........OlkOKKO....OKO.OkkkO.O',
      '..........OlkOKKO....OKO.OkkO.OO',
      '..........OlkOKKO....OKKOkkO..Ok',
      '..........OkkOKKO....OKKOkkO...O',
      '..........OhhOOhO....OhOOhhO....',
    ],
    ear: [
      '................................',
      '................................',
      '......OOO.......................',
      '...OOOsssO...OOOOOOOOOOOOOOO....',
      '..OlllOOYO..OsssllllllssssllOOO.',
      '..OlkkkkyOO.OlkkkkkkkkkkklsllkOO',
      '.OlkkkkkkkkOlklkkkkkkkkkklkklO.O',
      '.OlekkkkkkkklklkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'ONnkkOOkkkkkklkkkkkkkkkklkkklO.O',
      'OnnkO..OkkkkkkkkkkkkkkkkklkklO.O',
      'OnnnO...OkkkkkKKKKKKKKKKkkkklO.O',
      '.OOO.....OkKKOKKKKKKKKKKOOOOlO.O',
      '.........OOKKOKKKOOOOKKKOKKkkO.O',
      '..........OlkOKKO....OKO.OkkkO.O',
      '..........OlkOKKO....OKO.OkkkO.O',
      '..........OlkOKKO....OKO.OkkO.OO',
      '..........OlkOKKO....OKKOkkO..Ok',
      '..........OkkOKKO....OKKOkkO...O',
      '..........OhhOOhO....OhOOhhO....',
    ],
    tail1: [
      '................................',
      '................................',
      '................................',
      '...OOOO......OOOOOOOOOOOOOOO....',
      '..OlllsOOO..OsssllllllssssllOOO.',
      '..OlkkOsssO.OlkkkkkkkkkkklsllkOO',
      '.OlkkkkOOYOOlklkkkkkkkkkklkklO.O',
      '.OlekkkkkykOlklkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'ONnkkOOkkkkkklkkkkkkkkkklkkklO.O',
      'OnnkO..OkkkkkkkkkkkkkkkkklkklO.O',
      'OnnnO...OkkkkkKKKKKKKKKKkkkklO.O',
      '.OOO.....OkKKOKKKKKKKKKKOOOOlO.O',
      '.........OOKKOKKKOOOOKKKOKKkkO.O',
      '..........OlkOKKO....OKO.OkkkOOO',
      '..........OlkOKKO....OKO.OkkkOOk',
      '..........OlkOKKO....OKO.OkkO..O',
      '..........OlkOKKO....OKKOkkO....',
      '..........OkkOKKO....OKKOkkO....',
      '..........OhhOOhO....OhOOhhO....',
    ],
    tail2: [
      '................................',
      '................................',
      '................................',
      '...OOOO......OOOOOOOOOOOOOOO....',
      '..OlllsOOO..OsssllllllssssllOOO.',
      '..OlkkOsssO.OlkkkkkkkkkkklsllkOO',
      '.OlkkkkOOYOOlklkkkkkkkkkklkklO.O',
      '.OlekkkkkykOlklkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'ONnkkOOkkkkkklkkkkkkkkkklkkklO.O',
      'OnnkO..OkkkkkkkkkkkkkkkkklkklO.O',
      'OnnnO...OkkkkkKKKKKKKKKKkkkklOOO',
      '.OOO.....OkKKOKKKKKKKKKKOOOOlOOk',
      '.........OOKKOKKKOOOOKKKOKKkkO.O',
      '..........OlkOKKO....OKO.OkkkO..',
      '..........OlkOKKO....OKO.OkkkO..',
      '..........OlkOKKO....OKO.OkkO...',
      '..........OlkOKKO....OKKOkkO....',
      '..........OkkOKKO....OKKOkkO....',
      '..........OhhOOhO....OhOOhhO....',
    ],
  },
  lie: {
    base: [
      '...OOOO.........................',
      '..OlllsOOO......................',
      '..OlkkOsssO..OOOOOOOOOOOOOOO....',
      '.OlkkkkOOYOOlllssslllllsssslOOO.',
      '.OlekkkkkyklkkllkkkkkkkkklllllO.',
      'OlkkkkkkkkkkkkklkkkkkkkkkkkkklO.',
      'OlkkkkkkkkkkkkklkkkkkkkkkkkkklO.',
      'ONnkkOOkkkkkkklkkkkkkkOOOOOkklO.',
      'OnnkO..OkkkkkklkkkkkkOlkkkkOklO.',
      'OnnnO...OkkkkkkkkkkkOlkkkkkOklO.',
      '.OOO...OkkkKKkkkkkkkOkkkkkkkOlO.',
      '.......OOkkKKkkkkkkOkkkkkkkkOkO.',
      '.....OOOOOOOOKKKKOOKKKKKKKKKOkkO',
      '....OhlllkkkOKKKhhKKKKKKKKKOOOOO',
      '.....OOOOOOOOOOOOOOOOOOOOOOO....',
    ],
    chew: [
      '...OOOO.........................',
      '..OlllsOOO......................',
      '..OlkkOsssO..OOOOOOOOOOOOOOO....',
      '.OlkkkkOOYOOlllssslllllsssslOOO.',
      '.OlekkkkkyklkkllkkkkkkkkklllllO.',
      'OlkkkkkkkkkkkkklkkkkkkkkkkkkklO.',
      'OlkkkkkkkkkkkkklkkkkkkkkkkkkklO.',
      'ONnkkOOkkkkkkklkkkkkkkOOOOOkklO.',
      'OnnkkkOOkkkkkklkkkkkkOlkkkkOklO.',
      'OnnnkO..OkkkkkkkkkkkOlkkkkkOklO.',
      '.OOOO...kkkKKkkkkkkkOkkkkkkkOlO.',
      '.......OOkkKKkkkkkkOkkkkkkkkOkO.',
      '.....OOllOOOOKKKKOOKKKKKKKKKOkkO',
      '.....OhhkkkkOKKKhhKKKKKKKKKOOOOO',
      '......OOOOOOOOOOOOOOOOOOOOOO....',
    ],
    ear: [
      '...OOOsssO......................',
      '..OlllOOYO......................',
      '..OlkkkkyOO..OOOOOOOOOOOOOOO....',
      '.OlkkkkkkkkOlllssslllllsssslOOO.',
      '.OlekkkkkkklkkllkkkkkkkkklllllO.',
      'OlkkkkkkkkkkkkklkkkkkkkkkkkkklO.',
      'OlkkkkkkkkkkkkklkkkkkkkkkkkkklO.',
      'ONnkkOOkkkkkkklkkkkkkkOOOOOkklO.',
      'OnnkO..OkkkkkklkkkkkkOlkkkkOklO.',
      'OnnnO...OkkkkkkkkkkkOlkkkkkOklO.',
      '.OOO...OkkkKKkkkkkkkOkkkkkkkOlO.',
      '.......OOkkKKkkkkkkOkkkkkkkkOkO.',
      '.....OOOOOOOOKKKKOOKKKKKKKKKOkkO',
      '....OhlllkkkOKKKhhKKKKKKKKKOOOOO',
      '.....OOOOOOOOOOOOOOOOOOOOOOO....',
    ],
  },
  sleep: {
    base: [
      '........OOO.....................',
      '.......OsssO....................',
      '.....OOOOOYOOOOOOOOOOOOOOOOO....',
      '....OllllOyllOOOsslllllsssslOOO.',
      '...OlkkkkkkkklllOOkkkkkkklllllO.',
      '...OkkkkkkkkkkkknnOkkkkkkkkkklO.',
      '...OkkkkkkkkkkkkNnOkkkkkkkkkklO.',
      '...OkOOOOOOOOOOOnnOkkkOOOOOkklO.',
      '...OkkkkkkkkkkkkOOkkkOlkkkkOklO.',
      '...OllllllkkkkkkkkkkOlkkkkkOklO.',
      '....OkkkkkkkkkkkkkkkOkkkkkkkOlO.',
      '.....KKKKKKKKKkkkkkOkkkkkkkkOkO.',
      '.....OOOOOOOOKKKKOOKKKKKKKKKOkkO',
      '....OhlllkkkOKKKhhKKKKKKKKKOOOOO',
      '.....OOOOOOOOOOOOOOOOOOOOOOO....',
    ],
    ear: [
      '.........OOO....................',
      '........OsssO...................',
      '.....OOOOOYOOOOOOOOOOOOOOOOO....',
      '....OllllOyllOOOsslllllsssslOOO.',
      '...OlkkkkkkkklllOOkkkkkkklllllO.',
      '...OkkkkkkkkkkkknnOkkkkkkkkkklO.',
      '...OkkkkkkkkkkkkNnOkkkkkkkkkklO.',
      '...OkOOOOOOOOOOOnnOkkkOOOOOkklO.',
      '...OkkkkkkkkkkkkOOkkkOlkkkkOklO.',
      '...OllllllkkkkkkkkkkOlkkkkkOklO.',
      '....OkkkkkkkkkkkkkkkOkkkkkkkOlO.',
      '.....KKKKKKKKKkkkkkOkkkkkkkkOkO.',
      '.....OOOOOOOOKKKKOOKKKKKKKKKOkkO',
      '....OhlllkkkOKKKhhKKKKKKKKKOOOOO',
      '.....OOOOOOOOOOOOOOOOOOOOOOO....',
    ],
  },
  front: {
    base: [
      '....................',
      '.........OO.........',
      '....OOO......OOO....',
      '....OskOOOOOOksO....',
      '...OkkkllssllkkkO...',
      '..OKkklllsllllkkKO..',
      '..OKkkllllllllkkKO..',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllslllkkKKO.',
      '.OKKkklllsslllkkKKO.',
      '.OKKkkkllllllkkkKKO.',
      '..OKkkklsslllkkkKO..',
      '..OKkkkllllllkkkKO..',
      '..OOOOkkkllkkkOOOO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OhhOkkkllkkkOhhO..',
      '..OOOOkkkllkkkOOOO..',
      '.....OkkkllkkkO.....',
      'OOOOOkkllssllkkOOOOO',
      'OsslOkkllllllkkOlssO',
      'OkkkOOekllllkeOOkkkO',
      'OYOO.OkkllllkkO.OOYO',
      '.y...OkkkllkkkO...y.',
      '......OkkkkkkO......',
      '......OnnnnnnO......',
      '......ONnnnnNO......',
      '......OnnnnnnO......',
      '.......OOOOOO.......',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
    ],
    eat: [
      '....................',
      '.........OO.........',
      '....OOO......OOO....',
      '....OskOOOOOOksO....',
      '...OkkkllssllkkkO...',
      '..OKkklllsllllkkKO..',
      '..OKkkllllllllkkKO..',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllslllkkKKO.',
      '.OKKkklllsslllkkKKO.',
      '.OKKkkkllllllkkkKKO.',
      '..OKkkklsslllkkkKO..',
      '..OKkkkllllllkkkKO..',
      '..OOOOkkkllkkkOOOO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OhhOkkkllkkkOhhO..',
      '..OOOOkkkllkkkOOOO..',
      '.....OkkkllkkkO.....',
      'OOOOOkkllssllkkOOOOO',
      'OsslOkkllllllkkOlssO',
      'OkkkOOekllllkeOOkkkO',
      'OYOO.OkkllllkkO.OOYO',
      '.y...OkkkllkkkO...y.',
      '......OkkkkkkO......',
      '......OkkkkkkO......',
      '......OnnnnnnO......',
      '......ONnnnnNO......',
      '......OnnnnnnO......',
      '.......OOOOOO.......',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
    ],
    reach: [
      '....................',
      '.........OO.........',
      '....OOO......OOO....',
      '....OskOOOOOOksO....',
      '...OkkkllssllkkkO...',
      '..OKkklllsllllkkKO..',
      '..OKkkllllllllkkKO..',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllslllkkKKO.',
      '.OKKkklllsslllkkKKO.',
      '.OKKkkkllllllkkkKKO.',
      '..OKkkklsslllkkkKO..',
      '..OKkkkllllllkkkKO..',
      '..OOOOkkkllkkkOOOO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OhhOkkkllkkkOhhO..',
      '..OOOOkkkllkkkOOOO..',
      '.....OkkkllkkkO.....',
      'OOOOOkkllssllkkOOOOO',
      'OsslOkkllllllkkOlssO',
      'OkkkOOekllllkeOOkkkO',
      'OYOO.OkkllllkkO.OOYO',
      '.y...OkkkllkkkO...y.',
      '......OkkkkkkO......',
      '......OkkkkkkO......',
      '......OkkkkkkO......',
      '......OnnnnnnO......',
      '......ONnnnnNO......',
      '......OnnnnnnO......',
      '.......OOOOOO.......',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
    ],
    reach_up: [
      '....................',
      '.........OO.........',
      '....OOO......OOO....',
      '....OskOOOOOOksO....',
      '...OkkkllssllkkkO...',
      '..OKkklllsllllkkKO..',
      '..OKkkllllllllkkKO..',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllslllkkKKO.',
      '.OKKkklllsslllkkKKO.',
      '.OKKkkkllllllkkkKKO.',
      '..OKkkklsslllkkkKO..',
      '..OKkkkllllllkkkKO..',
      '..OOOOkkkllkkkOOOO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OhhOkkkllkkkOhhO..',
      '..OOOOkkkllkkkOOOO..',
      '.....OkkkllkkkO.....',
      'OOOOOkkllssllkkOOOOO',
      'OsslOkkllllllkkOlssO',
      'OkkkOOekllllkeOOkkkO',
      'OYOO.OkkllllkkO.OOYO',
      '.y...OkkkllkkkO...y.',
      '......OkkkkkkO......',
      '......OkkkkkkO......',
      '......OnnnnnnO......',
      '......ONnnnnNO......',
      '......OnnnnnnO......',
      '.......OOOOOO.......',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
    ],
    ear: [
      '....................',
      '.........OO.........',
      '....OOO......OOO....',
      '....OskOOOOOOksO....',
      '...OkkkllssllkkkO...',
      '..OKkklllsllllkkKO..',
      '..OKkkllllllllkkKO..',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllslllkkKKO.',
      '.OKKkklllsslllkkKKO.',
      '.OKKkkkllllllkkkKKO.',
      '..OKkkklsslllkkkKO..',
      '..OKkkkllllllkkkKO..',
      '..OOOOkkkllkkkOOOO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OlkOkkkllkkkOklO..',
      '..OhhOkkkllkkkOhhO..',
      '..OOOOkkkllkkkOOOO..',
      '.....OkkkllkkkO.....',
      'OsslOkkllssllkkOOOOO',
      'OkkkOkkllllllkkOlssO',
      'OYOOOOekllllkeOOkkkO',
      '.y...OkkllllkkO.OOYO',
      '.....OkkkllkkkO...y.',
      '......OkkkkkkO......',
      '......OnnnnnnO......',
      '......ONnnnnNO......',
      '......OnnnnnnO......',
      '.......OOOOOO.......',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
    ],
  },
  back: {
    base: [
      '....................',
      '........OOOO........',
      '...OOOOOllllOOOOO...',
      '.OOsslOkkkkkkOlssOO.',
      '.OkkkOOkkkkkkOOkkkO.',
      '.OYOO..OOOOOO..OOYO.',
      '..y..OkkkkkkkkO..y..',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OOOOOOOOOO.....',
      '.....OkkllllkkO.....',
      '.....OllllllllO.....',
      '....OklllsslllkO....',
      '...OkklllsllllkkO...',
      '..OKkkllllllllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OKkkllllslllkkKO..',
      '..OKkklllsslllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OssklllOOOllkssO..',
      '..OslllllOlOllllsO..',
      '..OllllkkOlOkllllO..',
      '..OkkkklkOlOlkkkkO..',
      '..OkkkkkkOlOkkkkkO..',
      '...OOOOOkOlOOOOOO...',
      '...OKkkkOOlOkkkKO...',
      '...OlKkOOkkOOkKlO...',
      '...OlKO.OkkO.OKlO...',
      '...OlKO..OO..OKlO...',
      '...OhhO......OhhO...',
      '...OOOO......OOOO...',
    ],
    eat: [
      '........OOOO........',
      '...OOOOOllllOOOOO...',
      '.OOsslOkkkkkkOlssOO.',
      '.OkkkOOkkkkkkOOkkkO.',
      '.OYOO..OOOOOO..OOYO.',
      '..y..OkkkkkkkkO..y..',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OOOOOOOOOO.....',
      '.....OkkllllkkO.....',
      '.....OllllllllO.....',
      '....OklllsslllkO....',
      '...OkklllsllllkkO...',
      '..OKkkllllllllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OKkkllllslllkkKO..',
      '..OKkklllsslllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OssklllOOOllkssO..',
      '..OslllllOlOllllsO..',
      '..OllllkkOlOkllllO..',
      '..OkkkklkOlOlkkkkO..',
      '..OkkkkkkOlOkkkkkO..',
      '...OOOOOkOlOOOOOO...',
      '...OKkkkOOlOkkkKO...',
      '...OlKkOOkkOOkKlO...',
      '...OlKO.OkkO.OKlO...',
      '...OlKO..OO..OKlO...',
      '...OhhO......OhhO...',
      '...OOOO......OOOO...',
    ],
    tail1: [
      '....................',
      '........OOOO........',
      '...OOOOOllllOOOOO...',
      '.OOsslOkkkkkkOlssOO.',
      '.OkkkOOkkkkkkOOkkkO.',
      '.OYOO..OOOOOO..OOYO.',
      '..y..OkkkkkkkkO..y..',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OOOOOOOOOO.....',
      '.....OkkllllkkO.....',
      '.....OllllllllO.....',
      '....OklllsslllkO....',
      '...OkklllsllllkkO...',
      '..OKkkllllllllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OKkkllllslllkkKO..',
      '..OKkklllsslllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OssklllOOOllkssO..',
      '..OslllllOlOllllsO..',
      '..OllllkkOlOkllllO..',
      '..OkkkklkOlOlkkkkO..',
      '..OkkkkkkOlOkkkkkO..',
      '...OOOOOkOlOOOOOO...',
      '...OKkkkOOlOkkkKO...',
      '...OlKkO.OkkOkKlO...',
      '...OlKO..OkkOkKlO...',
      '...OlKO...OO.OKlO...',
      '...OhhO......OhhO...',
      '...OOOO......OOOO...',
    ],
    tail2: [
      '....................',
      '........OOOO........',
      '...OOOOOllllOOOOO...',
      '.OOsslOkkkkkkOlssOO.',
      '.OkkkOOkkkkkkOOkkkO.',
      '.OYOO..OOOOOO..OOYO.',
      '..y..OkkkkkkkkO..y..',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OOOOOOOOOO.....',
      '.....OkkllllkkO.....',
      '.....OllllllllO.....',
      '....OklllsslllkO....',
      '...OkklllsllllkkO...',
      '..OKkkllllllllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OKkkllllslllkkKO..',
      '..OKkklllsslllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OssklllOOOllkssO..',
      '..OslllllOlOllllsO..',
      '..OllllkkOlOkllllO..',
      '..OkkkklkOlOlkkkkO..',
      '..OkkkkkkOlOkkkkkO..',
      '...OOOOOkOlOOOOOO...',
      '...OKkkkOOlOkkkKO...',
      '...OlKkOOkO.OkKlO...',
      '...OlKkOkkO..OKlO...',
      '...OlKO.OO...OKlO...',
      '...OhhO......OhhO...',
      '...OOOO......OOOO...',
    ],
    ear: [
      '....................',
      '...OOOO.OOOO.OOOO...',
      '.OOsslOOllllOOlssOO.',
      '.OkkkOOkkkkkkOOkkkO.',
      '.OYOO..OkkkkO..OOYO.',
      '..y....OOOOOO....y..',
      '.....OkkkkkkkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OOOOOOOOOO.....',
      '.....OkkllllkkO.....',
      '.....OllllllllO.....',
      '....OklllsslllkO....',
      '...OkklllsllllkkO...',
      '..OKkkllllllllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OKkkllllslllkkKO..',
      '..OKkklllsslllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OssklllOOOllkssO..',
      '..OslllllOlOllllsO..',
      '..OllllkkOlOkllllO..',
      '..OkkkklkOlOlkkkkO..',
      '..OkkkkkkOlOkkkkkO..',
      '...OOOOOkOlOOOOOO...',
      '...OKkkkOOlOkkkKO...',
      '...OlKkOOkkOOkKlO...',
      '...OlKO.OkkO.OKlO...',
      '...OlKO..OO..OKlO...',
      '...OhhO......OhhO...',
      '...OOOO......OOOO...',
    ],
    reach: [
      '...OOOOOOOOOOOOOO...',
      '.OOsslOkkkkkkOlssOO.',
      '.OkkkOOkkkkkkOOkkkO.',
      '.OYOO..OOOOOO..OOYO.',
      '..y..OkkkkkkkkO..y..',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OOOOOOOOOO.....',
      '.....OkkllllkkO.....',
      '.....OllllllllO.....',
      '....OklllsslllkO....',
      '...OkklllsllllkkO...',
      '..OKkkllllllllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OKkkllllslllkkKO..',
      '..OKkklllsslllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OssklllOOOllkssO..',
      '..OslllllOlOllllsO..',
      '..OllllkkOlOkllllO..',
      '..OkkkklkOlOlkkkkO..',
      '..OkkkkkkOlOkkkkkO..',
      '...OOOOOkOlOOOOOO...',
      '...OKkkkOOlOkkkKO...',
      '...OlKkOOkkOOkKlO...',
      '...OlKO.OkkO.OKlO...',
      '...OlKO..OO..OKlO...',
      '...OhhO......OhhO...',
      '...OOOO......OOOO...',
    ],
    reach_up: [
      '........OOOO........',
      '...OOOOOllllOOOOO...',
      '.OOsslOkkkkkkOlssOO.',
      '.OkkkOOkkkkkkOOkkkO.',
      '.OYOO..OOOOOO..OOYO.',
      '..y..OkkkkkkkkO..y..',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OkkllllkkO.....',
      '.....OOOOOOOOOO.....',
      '.....OkkllllkkO.....',
      '.....OllllllllO.....',
      '....OklllsslllkO....',
      '...OkklllsllllkkO...',
      '..OKkkllllllllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OKkkllllslllkkKO..',
      '..OKkklllsslllkkKO..',
      '..OKkkllllllllkkKO..',
      '..OssklllOOOllkssO..',
      '..OslllllOlOllllsO..',
      '..OllllkkOlOkllllO..',
      '..OkkkklkOlOlkkkkO..',
      '..OkkkkkkOlOkkkkkO..',
      '...OOOOOkOlOOOOOO...',
      '...OKkkkOOlOkkkKO...',
      '...OlKkOOkkOOkKlO...',
      '...OlKO.OkkO.OKlO...',
      '...OlKO..OO..OKlO...',
      '...OhhO......OhhO...',
      '...OOOO......OOOO...',
    ],
  },
  stand: {
    base: [
      '....OOO..OO..OOO....',
      '....OskOOllOOksO....',
      '...OkkkllssllkkkO...',
      '..OKkklllsllllkkKO..',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllslllkkKKO.',
      '.OKKkklllsllllkkKKO.',
      '.OKKkkkllllllkkkKKO.',
      '.OKKOOOOOOOOOOOOKKO.',
      'OOOOOkkllssllkkOOOOO',
      'OsslOkkllllllkkOlssO',
      'OkkkOOekllllkeOOkkkO',
      'OYOOKOkkllllkkOKOOYO',
      '.yOKkOkkkllkkkOkKOy.',
      '..OKkkOkkkkkkOkkKO..',
      '..OlkkOnnnnnnOkklO..',
      '..OlkkONnnnnNOkklO..',
      '..OlkkOnnnnnnOkklO..',
      '..OlkO.OOOOOO.OklO..',
      '..OlkO........OklO..',
      '..OhhO........OhhO..',
      '..OOOO........OOOO..',
    ],
    chew: [
      '....OOO..OO..OOO....',
      '....OskOOllOOksO....',
      '...OkkkllssllkkkO...',
      '..OKkklllsllllkkKO..',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllslllkkKKO.',
      '.OKKkklllsllllkkKKO.',
      '.OKKkkkllllllkkkKKO.',
      '.OKKOOOOOOOOOOOOKKO.',
      'OOOOOkkllssllkkOOOOO',
      'OsslOkkllllllkkOlssO',
      'OkkkOOekllllkeOOkkkO',
      'OYOOKOkkllllkkOKOOYO',
      '.yOKkOkkkllkkkOkKOy.',
      '..OKkkOkkkkkkOkkKO..',
      '..OlkkOnnnnnnOkklO..',
      '..OlkkONnnnnNOkklO..',
      '..OlkkOnnnnnnOkklO..',
      '..OlkkOOnnnnOOkklO..',
      '..OlkO.OOOOOO.OklO..',
      '..OhhO........OhhO..',
      '..OOOO........OOOO..',
    ],
    ear: [
      '....OOO..OO..OOO....',
      '....OskOOllOOksO....',
      '...OkkkllssllkkkO...',
      '..OKkklllsllllkkKO..',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllllllkkKKO.',
      '.OKKkkllllslllkkKKO.',
      '.OKKkklllsllllkkKKO.',
      '.OKKkkkllllllkkkKKO.',
      '.OKKOOOOOOOOOOOOKKO.',
      'OsslOkkllssllkkOOOOO',
      'OkkkOkkllllllkkOlssO',
      'OYOOOOekllllkeOOkkkO',
      '.yOKKOkkllllkkOKOOYO',
      '..OKkOkkkllkkkOkKOy.',
      '..OKkkOkkkkkkOkkKO..',
      '..OlkkOnnnnnnOkklO..',
      '..OlkkONnnnnNOkklO..',
      '..OlkkOnnnnnnOkklO..',
      '..OlkO.OOOOOO.OklO..',
      '..OlkO........OklO..',
      '..OhhO........OhhO..',
      '..OOOO........OOOO..',
    ],
  },
  rise: {
    r1: [
      '................................',
      '................................',
      '................................',
      '.....................OOOOOOO....',
      '.................OOOOlssssllOOO.',
      '..............OOOllllkkkklsllkOO',
      '..........OOOOsslkkkkkkkklkklO.O',
      '...OOOO...OOkskkkkkkkkkklkkklO.O',
      '..OlllsOOOkkOllkkkkkkkkklkkklO.O',
      '..OlkkOsssOkOklkkkkkkkkklkkklO.O',
      '.OlkkkkOOYOOlkkkkkkkkkkklkkklO.O',
      '.OlekkkkkykOllkkkkkkkkkkklkklO.O',
      'OlkkkkkkkkkkklkkkkkkkKKKkkkklO.O',
      'OlkkkkkkkkkkklkkkKKKKKKKOOOOlO.O',
      'ONnkkOOkkkkkkkKKKKKKKKKKOKKkkO.O',
      'OnnkO..OkkkkkkKKKOOOOOKO.OkkkO.O',
      'OnnnO...OkkkkkkkO....OKO.OkkkO.O',
      '.OOO..OklllllllkO....OKO.OkkO.OO',
      '.....OkkkkkkkkkkO....OKKOkkO..Ok',
      '.....OhhKKKKKKKO.....OKKOkkO...O',
      '......OOOOOOOOO......OhOOhhO....',
    ],
    r2: [
      '................................',
      '................................',
      '................................',
      '................OOOOOOOOOOOO....',
      '...OOOO......OOOllllllssssllOOO.',
      '..OlllsOOO..OssskkkkkkkkklsllkOO',
      '..OlkkOsssO.OlkkkkkkkkkkklkklO.O',
      '.OlkkkkOOYOOlklkkkkkkkkklkkklO.O',
      '.OlekkkkkykOlklkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'OlkkkkkkkkkkklkkkkkkkkkklkkklO.O',
      'ONnkkOOkkkkkklkkkkkkkkkkklkklO.O',
      'OnnkO..OkkkkkkkkKKKKKKKKkkkklO.O',
      'OnnnO...OkkkkkKKKKKKKKKKOOOOlO.O',
      '.OOO.....OkKKOKKKOOOOKKKOKKkkO.O',
      '.........OOKKOKKO....OKO.OkkkO.O',
      '..........OlkOKKO....OKO.OkkkO.O',
      '..........OlkOKKO....OKO.OkkO.OO',
      '..........OlkOKKO....OKKOkkO..Ok',
      '..........OlkOKKO....OKKOkkO...O',
      '..........OkkOKKO....OhOOhhO....',
    ],
  },
};

export const COW_WHITE: Record<string, Record<string, Record<string, [number, number, string][]>>> = {
  side: {
    belly: {
      base: [[15, 13, 'w'], [16, 13, 'W'], [17, 13, 'W'], [18, 13, 'W'], [19, 13, 'w'], [17, 12, 'w']],
    },
    leg: {
      base: [[26, 17, 'W'], [27, 17, 'w'], [25, 18, 'W'], [26, 18, 'W'], [25, 19, 'W'], [26, 19, 'w']],
    },
    face: {
      base: [[3, 5, 'W'], [4, 5, 'w']],
    },
  },
  lie: {
    belly: {
      base: [[13, 11, 'w'], [14, 11, 'W'], [15, 11, 'W'], [16, 11, 'W'], [17, 11, 'w']],
    },
    leg: {
      base: [[14, 13, 'W'], [15, 13, 'W'], [15, 12, 'w']],
    },
    face: {
      base: [[3, 2, 'W'], [4, 2, 'w']],
    },
  },
  sleep: {
    belly: {
      base: [[14, 11, 'w'], [15, 11, 'W'], [16, 11, 'W'], [17, 11, 'w']],
    },
    leg: {
      base: [[14, 13, 'W'], [15, 13, 'W'], [15, 12, 'w']],
    },
    face: {
      base: [[6, 4, 'W'], [7, 4, 'w']],
    },
  },
  front: {
    belly: {
      base: [[2, 9, 'w'], [2, 10, 'W'], [17, 9, 'w'], [17, 10, 'W']],
    },
    leg: {
      base: [[3, 16, 'W'], [4, 16, 'W'], [3, 17, 'W'], [4, 17, 'w']],
    },
    face: {
      base: [[9, 22, 'W'], [10, 22, 'W'], [9, 23, 'w']],
      eat: [[9, 22, 'W'], [10, 22, 'W'], [9, 23, 'w']],
      reach: [[9, 22, 'W'], [10, 22, 'W'], [9, 23, 'w']],
      reach_up: [[9, 22, 'W'], [10, 22, 'W'], [9, 23, 'w']],
      ear: [[9, 22, 'W'], [10, 22, 'W'], [9, 23, 'w']],
    },
  },
  stand: {
    belly: {
      base: [[2, 6, 'w'], [2, 7, 'W'], [17, 6, 'w'], [17, 7, 'W']],
    },
    leg: {
      base: [[3, 19, 'W'], [4, 19, 'w'], [3, 20, 'W'], [4, 20, 'W']],
    },
    face: {
      base: [[9, 11, 'W'], [10, 11, 'W'], [9, 12, 'w']],
    },
  },
  back: {
    belly: {
      base: [[7, 24, 'w'], [8, 24, 'W'], [12, 24, 'W'], [13, 24, 'w']],
    },
    leg: {
      base: [[4, 27, 'W'], [5, 27, 'w'], [4, 28, 'W'], [5, 28, 'W'], [4, 29, 'W'], [5, 29, 'w']],
    },
    face: {
      base: [],
    },
  },
};
