// F1 fattening steers of 石黒牛舎: pixel rows generated from hand-tuned shapes
// (52 10.4, 4.3). Letters: O outline #1B1733, k coat #2B2A30, l light #45434C,
// s sheen #6E6A78, K deepest #1B1733, e eye #0B0B14, n muzzle #3A3F48, N its
// wet shine #9AA0A8, Y ear tag #FFD23F, y tag shade #D9A441, h hoof #3A3F48,
// W white #E8E4D8, w white shade #C8C2B4. Every frame faces left (the side
// views) or the viewer; the right-facing cows are mirrored at run time.

export const COW_FRAMES: Record<string, Record<string, string[]>> = {
  side: {
    base: [
      '................................',
      '................................',
      '...........OOOOOOOOOOOOOOOO.....',
      '...OOOOOOOOllllllllllllllllO....',
      '..OllllOOOlkkkssssssssssskklOO..',
      '.OlkkkkkkkOOkkkkkkkkkkkkkkkkOkO.',
      'OlkkkkkOkkkkkkkkkkkkkkkkkkkkOkO.',
      'OlkkkekkOOOOkkkkkkkkkkkkkkkkOlO.',
      'OlkkkkkkkOkkYkkkkkkkkkkkkkkkOkO.',
      'OnkkkkkkkOkkykkkkkkkkkkkkkkkOkO.',
      'OnNkkkkkOkkkkkkkkkkkkkkkkkkkOlO.',
      'OnnkkkkkOkkkkkkkkkkkkkkkKkkkOkO.',
      'OlnnkkOO.OkkkkkkkkkkkkkkKkkkOkO.',
      '.OOOOO...OKkkkkkkkkkkkkkKkkkklO.',
      '..........OKkkKKKKKKKKKKKkkklkO.',
      '...........OkkOKKOOOOOKKOkkkklO.',
      '...........OkkOKKO...OKKOOkOOO..',
      '...........OkkOKKO...OKKOOkO....',
      '...........OhhOhhO...OhhOOhO....',
      '............OO.OO.....OO..O.....',
      '................................',
    ],
    chew: [
      '................................',
      '................................',
      '...........OOOOOOOOOOOOOOOO.....',
      '...OOOOOOOOllllllllllllllllO....',
      '..OllllOOOlkkkssssssssssskklOO..',
      '.OlkkkkkkkOOkkkkkkkkkkkkkkkkOkO.',
      'OlkkkkkOkkkkkkkkkkkkkkkkkkkkOkO.',
      'OlkkkekkOOOOkkkkkkkkkkkkkkkkOlO.',
      'OlkkkkkkkOkkYkkkkkkkkkkkkkkkOkO.',
      'OnkkkkkkkOkkykkkkkkkkkkkkkkkOkO.',
      'OnNkkkkkOkkkkkkkkkkkkkkkkkkkOlO.',
      'OnnkkkkkOkkkkkkkkkkkkkkkKkkkOkO.',
      'OlnnkkOO.OkkkkkkkkkkkkkkKkkkOkO.',
      '.OlkkO...OKkkkkkkkkkkkkkKkkkklO.',
      '..OOO.....OKkkKKKKKKKKKKKkkklkO.',
      '...........OkkOKKOOOOOKKOkkkklO.',
      '...........OkkOKKO...OKKOOkOOO..',
      '...........OkkOKKO...OKKOOkO....',
      '...........OhhOhhO...OhhOOhO....',
      '............OO.OO.....OO..O.....',
      '................................',
    ],
    ear: [
      '................................',
      '................................',
      '...........OOOOOOOOOOOOOOOO.....',
      '...OOOOOOOOllllllllllllllllO....',
      '..OlllllllOOkkssssssssssskklOO..',
      '.OlkkkkOkkkkkkkkkkkkkkkkkkkkOkO.',
      'OlkkkkkkOOOOkkkkkkkkkkkkkkkkOkO.',
      'OlkkkekkkOkkYkkkkkkkkkkkkkkkOlO.',
      'OlkkkkkkkOkkykkkkkkkkkkkkkkkOkO.',
      'OnkkkkkkkOkkkkkkkkkkkkkkkkkkOkO.',
      'OnNkkkkkOkkkkkkkkkkkkkkkkkkkOlO.',
      'OnnkkkkkOkkkkkkkkkkkkkkkKkkkOkO.',
      'OlnnkkOO.OkkkkkkkkkkkkkkKkkkOkO.',
      '.OOOOO...OKkkkkkkkkkkkkkKkkkklO.',
      '..........OKkkKKKKKKKKKKKkkklkO.',
      '...........OkkOKKOOOOOKKOkkkklO.',
      '...........OkkOKKO...OKKOOkOOO..',
      '...........OkkOKKO...OKKOOkO....',
      '...........OhhOhhO...OhhOOhO....',
      '............OO.OO.....OO..O.....',
      '................................',
    ],
    tail1: [
      '................................',
      '................................',
      '...........OOOOOOOOOOOOOOOO.....',
      '...OOOOOOOOllllllllllllllllO....',
      '..OllllOOOlkkkssssssssssskklOO..',
      '.OlkkkkkkkOOkkkkkkkkkkkkkkkkOkO.',
      'OlkkkkkOkkkkkkkkkkkkkkkkkkkkOkO.',
      'OlkkkekkOOOOkkkkkkkkkkkkkkkkOlO.',
      'OlkkkkkkkOkkYkkkkkkkkkkkkkkkOkO.',
      'OnkkkkkkkOkkykkkkkkkkkkkkkkkOkO.',
      'OnNkkkkkOkkkkkkkkkkkkkkkkkkkOlO.',
      'OnnkkkkkOkkkkkkkkkkkkkkkKkkkOkO.',
      'OlnnkkOO.OkkkkkkkkkkkkkkKkkkOkO.',
      '.OOOOO...OKkkkkkkkkkkkkkKkkkOlkO',
      '..........OKkkKKKKKKKKKKKkkkOklO',
      '...........OkkOKKOOOOOKKOkkkOlkO',
      '...........OkkOKKO...OKKOOkO.OO.',
      '...........OkkOKKO...OKKOOkO....',
      '...........OhhOhhO...OhhOOhO....',
      '............OO.OO.....OO..O.....',
      '................................',
    ],
    tail2: [
      '................................',
      '................................',
      '...........OOOOOOOOOOOOOOOO.....',
      '...OOOOOOOOllllllllllllllllO....',
      '..OllllOOOlkkkssssssssssskklOO..',
      '.OlkkkkkkkOOkkkkkkkkkkkkkkkkOkO.',
      'OlkkkkkOkkkkkkkkkkkkkkkkkkkKkO..',
      'OlkkkekkOOOOkkkkkkkkkkkkkkkKkO..',
      'OlkkkkkkkOkkYkkkkkkkkkkkkkkKlO..',
      'OnkkkkkkkOkkykkkkkkkkkkkkkkKkO..',
      'OnNkkkkkOkkkkkkkkkkkkkkkkkkKkO..',
      'OnnkkkkkOkkkkkkkkkkkkkkkKkkklO..',
      'OlnnkkOO.OkkkkkkkkkkkkkkKkkkkO..',
      '.OOOOO...OKkkkkkkkkkkkkkKkklkO..',
      '..........OKkkKKKKKKKKKKKkkklO..',
      '...........OkkOKKOOOOOKKOkklkO..',
      '...........OkkOKKO...OKKOOkOO...',
      '...........OkkOKKO...OKKOOkO....',
      '...........OhhOhhO...OhhOOhO....',
      '............OO.OO.....OO..O.....',
      '................................',
    ],
  },
  lie: {
    base: [
      '..OOOOO.........................',
      '.OllllOO........................',
      'OlkkkkkOOOOO..........OOOO......',
      'OlkkkkkkllllOOOOOOOOOOllllOOO...',
      'OlkkekOOOYkkllllllllllsssklllO..',
      'OlkkkkkOkykkkkkssssssskkkkkkkO..',
      'OnkkkkkOkkkkkkkkkkkkkkkkkkkkklO.',
      'OnNkkkkOkkkkkKkkkkkkkkkkkkkkkkO.',
      'OnnkkkOOkkkkkKkkkkkkkkkkkkkkkkO.',
      'OlnnkO.OkkkkkKkkkkkkkkkkkkkkkkO.',
      '.OOOO..OkkkkkKkkkkkkkkkkkkkkkkO.',
      '......OKKkkkkKkkkkkkkKKKKKkkkOO.',
      '......OKKKKKkkkkkkkkkKKKKKkkkkkO',
      '......OKKKKKKKKKKKKKKKKKKKKKOkkO',
      '.......OOOOOOOOOOOOOOOOOOOOO.OO.',
    ],
    chew: [
      '..OOOOO.........................',
      '.OllllOO........................',
      'OlkkkkkOOOOO..........OOOO......',
      'OlkkkkkkllllOOOOOOOOOOllllOOO...',
      'OlkkekOOOYkkllllllllllsssklllO..',
      'OlkkkkkOkykkkkkssssssskkkkkkkO..',
      'OnkkkkkOkkkkkkkkkkkkkkkkkkkkklO.',
      'OnNkkkkOkkkkkKkkkkkkkkkkkkkkkkO.',
      'OnnkkkOOkkkkkKkkkkkkkkkkkkkkkkO.',
      'OlnnkO.OkkkkkKkkkkkkkkkkkkkkkkO.',
      '.OlkO..OkkkkkKkkkkkkkkkkkkkkkkO.',
      '..OO..OKKkkkkKkkkkkkkKKKKKkkkOO.',
      '......OKKKKKkkkkkkkkkKKKKKkkkkkO',
      '......OKKKKKKKKKKKKKKKKKKKKKOkkO',
      '.......OOOOOOOOOOOOOOOOOOOOO.OO.',
    ],
    ear: [
      '..OOOOO.........................',
      '.OlllllOOO......................',
      'OlkkkkklllOO..........OOOO......',
      'OlkkkkOOOYllOOOOOOOOOOllllOOO...',
      'OlkkekkOkykkllllllllllsssklllO..',
      'OlkkkkkOkkkkkkkssssssskkkkkkkO..',
      'OnkkkkkOkkkkkkkkkkkkkkkkkkkkklO.',
      'OnNkkkkOkkkkkKkkkkkkkkkkkkkkkkO.',
      'OnnkkkOOkkkkkKkkkkkkkkkkkkkkkkO.',
      'OlnnkO.OkkkkkKkkkkkkkkkkkkkkkkO.',
      '.OOOO..OkkkkkKkkkkkkkkkkkkkkkkO.',
      '......OKKkkkkKkkkkkkkKKKKKkkkOO.',
      '......OKKKKKkkkkkkkkkKKKKKkkkkkO',
      '......OKKKKKKKKKKKKKKKKKKKKKOkkO',
      '.......OOOOOOOOOOOOOOOOOOOOO.OO.',
    ],
  },
  sleep: {
    base: [
      '................................',
      '................................',
      '...........OOO........OOOO......',
      '.........OOlllOOOOOOOOllllOOO...',
      '........OllOOYlllllOOlsssklllO..',
      '.......OlkkkkykkkkkkOskkkkkkkO..',
      '.......OkkkkkkkkkkkkOkkkkkkkklO.',
      '.......OkkkkOkkkkkkOOkkkkkkkkkO.',
      '........OkkkkOOOOOOkkkkkkkkkkkO.',
      '........OkkkkKkkkkkskkkkkkkkkkO.',
      '.......OOkkkkKksssskkkkkkkkkkkO.',
      '......OKKKKKkkkkkkkkkKKKKKkkkOO.',
      '......OKKKKKkkkkkkkkkKKKKKkkkkkO',
      '......OKKKKKKKKKKKKKKKKKKKKKOkkO',
      '.......OOOOOOOOOOOOOOOOOOOOO.OO.',
    ],
    ear: [
      '................................',
      '...........OOO..................',
      '..........OlllO.......OOOO......',
      '.........OOOOYOOOOOOOOllllOOO...',
      '........OllkkylllllOOlsssklllO..',
      '.......OlkkkkkkkkkkkOskkkkkkkO..',
      '.......OkkkkkkkkkkkkOkkkkkkkklO.',
      '.......OkkkkOkkkkkkOOkkkkkkkkkO.',
      '........OkkkkOOOOOOkkkkkkkkkkkO.',
      '........OkkkkKkkkkkskkkkkkkkkkO.',
      '.......OOkkkkKksssskkkkkkkkkkkO.',
      '......OKKKKKkkkkkkkkkKKKKKkkkOO.',
      '......OKKKKKkkkkkkkkkKKKKKkkkkkO',
      '......OKKKKKKKKKKKKKKKKKKKKKOkkO',
      '.......OOOOOOOOOOOOOOOOOOOOO.OO.',
    ],
  },
  front: {
    base: [
      '....................',
      '...OOOOOOOOOOOOOO...',
      '..OlllllllsllllllO..',
      '.OlkkkkkklskkkkkklO.',
      '.OkkkkkkkkskkkkkkkO.',
      '.OkkkkkkkkkkkkkkkkO.',
      'OlkkkkOOOOOOOOkkkklO',
      'OkkkkkOkkkkkkOkkkkkO',
      'OkOOOOOkkkkkkOOOOOkO',
      '.OkkkklkkkkkkkkkkkO.',
      'OkkkOOOekkkkeOOOkkkO',
      '.OYOkkOkkkkkkOkkOYO.',
      '..ykKKOkkkkkkOKKky..',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OKKOknNnnkOKKO...',
      '...OKKOknkknkOKKO...',
      '...OhhOOOOOOOOhhO...',
      '....OO........OO....',
    ],
    eat: [
      '....................',
      '...OOOOOOOOOOOOOO...',
      '..OlllllllsllllllO..',
      '.OlkkkkkklskkkkkklO.',
      '.OkkkkkkkkskkkkkkkO.',
      '.OkkkkkkkkkkkkkkkkO.',
      'OlkkkkkkkkkkkkkkkklO',
      'OkkkkkOOOOOOOOkkkkkO',
      'OkkkkkOkkkkkkOkkkkkO',
      '.OOOOOOkkkkkkOOOOOO.',
      '.OkkkklkkkkkkkkkkkO.',
      'OkkkOOOekkkkeOOOkkkO',
      '.OYOKKOkkkkkkOKKOYO.',
      '..yOKKkkkkkkkkKKOy..',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OKKOknNnnkOKKO...',
      '...OhhOknkknkOhhO...',
      '....OO.OOOOOO.OO....',
    ],
    reach: [
      '....................',
      '...OOOOOOOOOOOOOO...',
      '..OlllllllsllllllO..',
      '.OlkkkkkklskkkkkklO.',
      '.OkkkkkkkkskkkkkkkO.',
      '.OkkkkkkkkkkkkkkkkO.',
      'OlkkkkkkkkkkkkkkkklO',
      'OkkkkkkkkkkkkkkkkkkO',
      'OkkkkkOOOOOOOOkkkkkO',
      '.OkkkkOkkkkkkOkkkkO.',
      '.OOOOOOkkkkkkOOOOOO.',
      '.OkkkklkkkkkkkkkkkO.',
      'OkkkOOOekkkkeOOOkkkO',
      '.OYOKKkkkkkkkkKKOYO.',
      '..yOKKkkkkkkkkKKOy..',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OhhOknNnnkOhhO...',
      '....OOOknkknkOOO....',
    ],
    reach_up: [
      '....................',
      '...OOOOOOOOOOOOOO...',
      '..OlllllllsllllllO..',
      '.OlkkkkkklskkkkkklO.',
      '.OkkkkkkkkskkkkkkkO.',
      '.OkkkkkkkkkkkkkkkkO.',
      'OlkkkkkkkkkkkkkkkklO',
      'OkkkkkOOOOOOOOkkkkkO',
      'OkkkkkOkkkkkkOkkkkkO',
      '.OOOOOOkkkkkkOOOOOO.',
      '.OkkkklkkkkkkkkkkkO.',
      'OkkkOOOekkkkeOOOkkkO',
      '.OYOKKOkkkkkkOKKOYO.',
      '..yOKKkkkkkkkkKKOy..',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OKKOknNnnkOKKO...',
      '...OhhOknkknkOhhO...',
      '....OO.OOOOOO.OO....',
    ],
    ear: [
      '....................',
      '...OOOOOOOOOOOOOO...',
      '..OlllllllsllllllO..',
      '.OlkkkkkklskkkkkklO.',
      '.OkkkkkkkkskkkkkkkO.',
      '.OkkkkkkkkkkkkkkkkO.',
      'OlkkkkOOOOOOOOkkkklO',
      'OkkkkkOkkkkkkOkkkkkO',
      'OOOOOOOkkkkkkOOOOOkO',
      'OkkkkklkkkkkkkkkkkO.',
      '.OYOOOOekkkkeOOOkkkO',
      '..ykkkOkkkkkkOkkOYO.',
      '..OkKKOkkkkkkOKKky..',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OKKOkkkkkkOKKO...',
      '...OKKOknNnnkOKKO...',
      '...OKKOknkknkOKKO...',
      '...OhhOOOOOOOOhhO...',
      '....OO........OO....',
    ],
  },
  back: {
    base: [
      '....................',
      '....................',
      '...OOOOOOOOOOOOOO...',
      '.OOlllllKllKlllllOO.',
      'OllkksssKkkKssskkllO',
      '.OYkkkkkKkkKkkkkkYO.',
      '.OykkkkkKllKkkkkkyO.',
      'OkkkkkkkKkkKkkkkkkkO',
      '.OkkkkkkKkkKkkkkkkO.',
      '.OkkkkkkKllKkkkkkkO.',
      '.OkkkkkkKkkKkkkkkkO.',
      '.OkkkkKkKkkKkkkkKkO.',
      '..OkkkKkKllKkkkkkO..',
      '..OkkkKkkkkkkkkkkO..',
      '...OkkkOOkkOOkkkO...',
      '...OkkkOOllOOkkkO...',
      '...OkkkO.OO.OkkkO...',
      '...OkkkO....OkkkO...',
      '...OhhhO....OhhhO...',
      '....OOO......OOO....',
    ],
    tail1: [
      '....................',
      '....................',
      '...OOOOOOOOOOOOOO...',
      '.OOlllllKllKlllllOO.',
      'OllkksssKkkKssskkllO',
      '.OYkkkkkkKkKkkkkkYO.',
      '.OykkkkkkKlKkkkkkyO.',
      'OkkkkkkkkKkKkkkkkkkO',
      '.OkkkkkkkKkKkkkkkkO.',
      '.OkkkkkkkKlKkkkkkkO.',
      '.OkkkkkkkKkKkkkkkkO.',
      '.OkkkkKkkKkKkkkkKkO.',
      '..OkkkKkkKlKkkkkkO..',
      '..OkkkKkkkkkkkkkkO..',
      '...OkkkOOOkkOkkkO...',
      '...OkkkO.OllOkkkO...',
      '...OkkkO..OOOkkkO...',
      '...OkkkO....OkkkO...',
      '...OhhhO....OhhhO...',
      '....OOO......OOO....',
    ],
    tail2: [
      '....................',
      '....................',
      '...OOOOOOOOOOOOOO...',
      '.OOlllllKllKlllllOO.',
      'OllkksssKkkKssskkllO',
      '.OYkkkkkKkKkkkkkkYO.',
      '.OykkkkkKlKkkkkkkyO.',
      'OkkkkkkkKkKkkkkkkkkO',
      '.OkkkkkkKkKkkkkkkkO.',
      '.OkkkkkkKlKkkkkkkkO.',
      '.OkkkkkkKkKkkkkkkkO.',
      '.OkkkkKkKkKkkkkkKkO.',
      '..OkkkKkKlKkkkkkkO..',
      '..OkkkKkkkkkkkkkkO..',
      '...OkkkOkkOOOkkkO...',
      '...OkkkOllO.OkkkO...',
      '...OkkkOOO..OkkkO...',
      '...OkkkO....OkkkO...',
      '...OhhhO....OhhhO...',
      '....OOO......OOO....',
    ],
    ear: [
      '....................',
      '....................',
      '.OOOOOOOOOOOOOOOO...',
      'OlllllllKllKlllllOO.',
      '.OkkksssKkkKssskkllO',
      '.OYkkkkkKkkKkkkkkYO.',
      '.OykkkkkKllKkkkkkyO.',
      'OkkkkkkkKkkKkkkkkkkO',
      '.OkkkkkkKkkKkkkkkkO.',
      '.OkkkkkkKllKkkkkkkO.',
      '.OkkkkkkKkkKkkkkkkO.',
      '.OkkkkKkKkkKkkkkKkO.',
      '..OkkkKkKllKkkkkkO..',
      '..OkkkKkkkkkkkkkkO..',
      '...OkkkOOkkOOkkkO...',
      '...OkkkOOllOOkkkO...',
      '...OkkkO.OO.OkkkO...',
      '...OkkkO....OkkkO...',
      '...OhhhO....OhhhO...',
      '....OOO......OOO....',
    ],
    reach: [
      '....................',
      '.OOO............OOO.',
      'OlllOOOOOOOOOOOOlllO',
      '.OYkllllKllKllllkYO.',
      '.OykksssKkkKssskkyO.',
      '.OkkkkkkKkkKkkkkkkO.',
      '.OkkkkkkKllKkkkkkkO.',
      'OkkkkkkkKkkKkkkkkkkO',
      '.OkkkkkkKkkKkkkkkkO.',
      '.OkkkkkkKllKkkkkkkO.',
      '.OkkkkkkKkkKkkkkkkO.',
      '.OkkkkKkKkkKkkkkKkO.',
      '..OkkkKkKllKkkkkkO..',
      '..OkkkKkkkkkkkkkkO..',
      '...OkkkOOkkOOkkkO...',
      '...OkkkOOllOOkkkO...',
      '...OkkkO.OO.OkkkO...',
      '...OkkkO....OkkkO...',
      '...OhhhO....OhhhO...',
      '....OOO......OOO....',
    ],
    reach_up: [
      '....................',
      '....................',
      '.OOOOOOOOOOOOOOOOOO.',
      'OlllllllKllKlllllllO',
      '.OYkksssKkkKssskkYO.',
      '.OykkkkkKkkKkkkkkyO.',
      '.OkkkkkkKllKkkkkkkO.',
      'OkkkkkkkKkkKkkkkkkkO',
      '.OkkkkkkKkkKkkkkkkO.',
      '.OkkkkkkKllKkkkkkkO.',
      '.OkkkkkkKkkKkkkkkkO.',
      '.OkkkkKkKkkKkkkkKkO.',
      '..OkkkKkKllKkkkkkO..',
      '..OkkkKkkkkkkkkkkO..',
      '...OkkkOOkkOOkkkO...',
      '...OkkkOOllOOkkkO...',
      '...OkkkO.OO.OkkkO...',
      '...OkkkO....OkkkO...',
      '...OhhhO....OhhhO...',
      '....OOO......OOO....',
    ],
  },
  rise: {
    r1: [
      '................................',
      '................................',
      '................................',
      '.........................OOO....',
      '.....................OOOOlllOO..',
      '.................OOOOllllkkkOlO.',
      '.....OOOO.OOO.OOOllllkkkkkkkOkO.',
      '...OOllllOlllOlllkkkkkkkkkkkOlO.',
      '..OllkkkOOOOklkkkkkkkkkkkkkkOkO.',
      '..OlkkkkkkkkkkkkkkkkkkkkkkkkOlO.',
      '.OlkkekkOOkkkkkkkkkkkkkkkkkkOkO.',
      '.OlkkkkkOkOYkkkkkkkkkkkkKkkkOlO.',
      'OlkkkkkOkkkykkkkkkkkkkkkKkkkOkO.',
      'OnkkkkkOkkkkkkkkkkkkkkkkKkkkklO.',
      'OnnkkkO.OkkkkkkkkkkkkkkkKkkklkO.',
      '.OnOOO..OkkkkkkkkkkkkkKKOkkkklO.',
      '.........OkkkkkkkkkOOOKKOOkOOO..',
      '........OKKKKKKkOOO..OKKOOkO....',
      '........OKKKKKKO.....OhhOOhO....',
      '.........OOOOOO.......OO..O.....',
      '................................',
    ],
    r2: [
      '................................',
      '................................',
      '.........................OO.....',
      '................OOOOOOOOOllO....',
      '.....OOOO.OOOOOOlllllllllkklOO..',
      '...OOllllOllllllkkkkkkkkkkkkOlO.',
      '..OllkkkOOOOkkkkkkkkkkkkkkkkOkO.',
      '..OlkkkkkkkkkkkkkkkkkkkkkkkkOlO.',
      '.OlkkekkOOkkkkkkkkkkkkkkkkkkOkO.',
      '.OlkkkkkOkOYkkkkkkkkkkkkkkkkOlO.',
      'OlkkkkkkOkkykkkkkkkkkkkkkkkkOkO.',
      'OnkkkkkkOkkkkkkkkkkkkkkkKkkkOlO.',
      'OnnkkkOOOkkkkkkkkkkkkkkkKkkkOkO.',
      'OlnkkO...OkkkkkkkkkkkkkkKkkkklO.',
      '.OOOO.....OOkkkkkkkkkkkkKkkklkO.',
      '...........OkkkkkkkkOOKKOkkkklO.',
      '...........OkkOKKOOO.OKKOOkOOO..',
      '...........OkkKKKO...OKKOOkO....',
      '...........OhhKKKO...OhhOOhO....',
      '............OOOOO.....OO..O.....',
      '................................',
    ],
  },
};

/** The little white of 1 cow in 5 (belly / a hind leg / the face), per pose and frame: [x, y, letter]. */
export const COW_WHITE: Record<string, Record<string, Record<string, [number, number, string][]>>> = {
  side: {
    belly: {
      base: [[17, 13, 'w'], [18, 13, 'w'], [19, 13, 'w'], [20, 13, 'w'], [16, 14, 'w'], [17, 14, 'W'], [18, 14, 'W'], [19, 14, 'W'], [20, 14, 'W'], [21, 14, 'w']],
      chew: [[17, 13, 'w'], [18, 13, 'w'], [19, 13, 'w'], [20, 13, 'w'], [16, 14, 'w'], [17, 14, 'W'], [18, 14, 'W'], [19, 14, 'W'], [20, 14, 'W'], [21, 14, 'w']],
      ear: [[17, 13, 'w'], [18, 13, 'w'], [19, 13, 'w'], [20, 13, 'w'], [16, 14, 'w'], [17, 14, 'W'], [18, 14, 'W'], [19, 14, 'W'], [20, 14, 'W'], [21, 14, 'w']],
      tail1: [[17, 13, 'w'], [18, 13, 'w'], [19, 13, 'w'], [20, 13, 'w'], [16, 14, 'w'], [17, 14, 'W'], [18, 14, 'W'], [19, 14, 'W'], [20, 14, 'W'], [21, 14, 'w']],
      tail2: [[17, 13, 'w'], [18, 13, 'w'], [19, 13, 'w'], [20, 13, 'w'], [16, 14, 'w'], [17, 14, 'W'], [18, 14, 'W'], [19, 14, 'W'], [20, 14, 'W'], [21, 14, 'w']],
    },
    leg: {
      base: [[25, 16, 'W'], [26, 16, 'W'], [25, 17, 'W'], [26, 17, 'W']],
      chew: [[25, 16, 'W'], [26, 16, 'W'], [25, 17, 'W'], [26, 17, 'W']],
      ear: [[25, 16, 'W'], [26, 16, 'W'], [25, 17, 'W'], [26, 17, 'W']],
      tail1: [[25, 16, 'W'], [26, 16, 'W'], [25, 17, 'W'], [26, 17, 'W']],
      tail2: [[25, 16, 'W'], [26, 16, 'W'], [25, 17, 'W'], [26, 17, 'W']],
    },
    face: {
      base: [[2, 6, 'w'], [3, 6, 'W'], [3, 7, 'W']],
      chew: [[2, 6, 'w'], [3, 6, 'W'], [3, 7, 'W']],
      ear: [[2, 6, 'w'], [3, 6, 'W'], [3, 7, 'W']],
      tail1: [[2, 6, 'w'], [3, 6, 'W'], [3, 7, 'W']],
      tail2: [[2, 6, 'w'], [3, 6, 'W'], [3, 7, 'W']],
    },
  },
  lie: {
    belly: {
      base: [[14, 12, 'w'], [15, 12, 'W'], [16, 12, 'W'], [17, 12, 'W'], [18, 12, 'W'], [19, 12, 'W'], [20, 12, 'w']],
      chew: [[14, 12, 'w'], [15, 12, 'W'], [16, 12, 'W'], [17, 12, 'W'], [18, 12, 'W'], [19, 12, 'W'], [20, 12, 'w']],
      ear: [[14, 12, 'w'], [15, 12, 'W'], [16, 12, 'W'], [17, 12, 'W'], [18, 12, 'W'], [19, 12, 'W'], [20, 12, 'w']],
    },
    leg: {
      base: [[22, 12, 'W'], [23, 12, 'W']],
      chew: [[22, 12, 'W'], [23, 12, 'W']],
      ear: [[22, 12, 'W'], [23, 12, 'W']],
    },
    face: {
      base: [[3, 3, 'W'], [2, 4, 'W']],
      chew: [[3, 3, 'W'], [2, 4, 'W']],
      ear: [[3, 3, 'W'], [2, 4, 'W']],
    },
  },
  sleep: {
    belly: {
      base: [[14, 12, 'w'], [15, 12, 'W'], [16, 12, 'W'], [17, 12, 'W'], [18, 12, 'W'], [19, 12, 'W'], [20, 12, 'w']],
      ear: [[14, 12, 'w'], [15, 12, 'W'], [16, 12, 'W'], [17, 12, 'W'], [18, 12, 'W'], [19, 12, 'W'], [20, 12, 'w']],
    },
    leg: {
      base: [[22, 12, 'W'], [23, 12, 'W']],
      ear: [[22, 12, 'W'], [23, 12, 'W']],
    },
    face: {
      base: [],
      ear: [],
    },
  },
  front: {
    belly: {
      base: [],
      eat: [],
      reach: [],
      reach_up: [],
      ear: [],
    },
    leg: {
      base: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'w']],
      eat: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'w']],
      reach: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'w']],
      reach_up: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'w']],
      ear: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'w']],
    },
    face: {
      base: [[9, 8, 'W'], [10, 8, 'W'], [10, 9, 'w']],
      eat: [[9, 9, 'W'], [10, 9, 'W'], [10, 10, 'w']],
      reach: [[9, 10, 'W'], [10, 10, 'W'], [10, 11, 'w']],
      reach_up: [[9, 9, 'W'], [10, 9, 'W'], [10, 10, 'w']],
      ear: [[9, 8, 'W'], [10, 8, 'W'], [10, 9, 'w']],
    },
  },
  back: {
    belly: {
      base: [[8, 14, 'w'], [9, 14, 'W'], [10, 14, 'W'], [11, 14, 'w']],
      tail1: [[8, 14, 'w'], [9, 14, 'W'], [10, 14, 'W'], [11, 14, 'w']],
      tail2: [[8, 14, 'w'], [9, 14, 'W'], [10, 14, 'W'], [11, 14, 'w']],
      ear: [[8, 14, 'w'], [9, 14, 'W'], [10, 14, 'W'], [11, 14, 'w']],
      reach: [[8, 14, 'w'], [9, 14, 'W'], [10, 14, 'W'], [11, 14, 'w']],
      reach_up: [[8, 14, 'w'], [9, 14, 'W'], [10, 14, 'W'], [11, 14, 'w']],
    },
    leg: {
      base: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'W']],
      tail1: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'W']],
      tail2: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'W']],
      ear: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'W']],
      reach: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'W']],
      reach_up: [[14, 16, 'W'], [15, 16, 'W'], [14, 17, 'W'], [15, 17, 'W']],
    },
    face: {
      base: [],
      tail1: [],
      tail2: [],
      ear: [],
      reach: [],
      reach_up: [],
    },
  },
};
